AllCops:
  Include:
    - 'db/migrate/*'
    - 'Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Exclude:
    - 'Gemfile'

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 120

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - '='
    - '||='

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
