language: ruby

rvm:
  - 2.2

cache: bundler

sudo: false

services:
  - mysql

before_script:
  - rake db:create ; rake db:migrate

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - bundle exec rspec
  - bundle exec rubocop
