postgres:
  image: postgres
  ports:
    - "5432"

rails:
  build: .
  ports:
    - "3000:3000"
  links:
   - postgres
   - redis

redis:
  image: redis

nginx:
  build: ./nginx
  links:
    - web
  ports:
    - "80:80"