mysql_master:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_PASS=admin
    - REPLICATION_MASTER=true
    - REPLICATION_USER=admin
    - REPLICATION_PASS=admin

mysql_slave:
  image: tutum/mysql
  ports:
    - "3307:3306"
  environment:
    - MYSQL_PASS=admin
    - REPLICATION_SLAVE=true

rails:
  build: .
  ports:
    - "3000"
  links:
    - mysql
    - redis

resque:
  build: .
  links:
    - mysql
    - redis
  ports:
    - "5678"
  environment:
    - QUEUE=*
  command: rake environment resque:work

redis:
  image: redis

nginx:
  build: ./lib/docker_images/nginx
  links:
    - rails
  ports:
    - "80:80"
    - "443:443"
