mysqlmaster:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_PASS=admin
    - REPLICATION_MASTER=true

mysqlslave:
  image: tutum/mysql
  ports:
    - "3307:3306"
  environment:
    - MYSQL_PASS=admin
    - REPLICATION_SLAVE=true

rails:
  build: .
  ports:
    - "3000"
    - "1080"
  links:
    - mysqlmaster
    - mysqlslave

resque:
  build: .
  links:
    - mysqlmaster
    - mysqlslave
    - redis
  ports:
    - "5678"
  environment:
    - QUEUE=*
  command: rake environment resque:work

redis:
  image: redis

nginx:
  build: ./lib/docker_images/nginx
  links:
    - rails
  ports:
    - "80:80"
    - "443:443"
