mysql:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_PASS=admin

rails:
  build: .
  ports:
    - "3000"
  links:
   - mysql
   - redis

redis:
  image: redis

nginx:
  build: ./nginx
  links:
    - rails
  ports:
    - "80:80"
    - "443:443"