development:
  adapter: mysql2
  encoding: utf8
  database: knowmad_development
  username: admin
  password: admin
  host: mysql
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: knowmad_test
  username: travis

production:
  adapter: mysql2
  encoding: utf8
  host: mysql
  database: knowmad_production
  username: <%= ENV['KNOWMAD_PRODUCTION_DATABASE_USER'] %>
  password: <%= ENV['KNOWMAD_PRODUCTION_DATABASE_PASS'] %>
  pool: 5

