development: &default
  adapter: mysql2
  encoding: utf8
  database: knowmad_development
  pool: 5
  username: admin
  password: admin
  host: mysql

test:
  adapter: mysql2
  database: knowmad_test
  username: travis
  encoding: utf8
