development: &default
  adapter: postgresql
  encoding: unicode
  database: knowmad_development
  pool: 5
  username: postgres
  password:
  host: postgres

test:
  <<: *default
  database: knowmad_test
