development:
  adapter: mysql2
  encoding: utf8
  database: knowmad_development
  username: admin
  password: admin
  host: mysql

test:
  adapter: mysql2
  database: knowmad_test
  username: travis
  encoding: utf8

production:
  adapter: mysql2
  host: mysql
  encoding: utf8
  pool: 5
  database: knowmad_production
  username: <%= ENV['KNOWMAD_PRODUCTION_DATABASE_USER_NAME'] %>
  password: <%= ENV['KNOWMAD_PRODUCTION_DATABASE_PASSWORD'] %>
