# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5364bf5e498153f3b7294c4f7834e0f798cd507934e5b0ee6b6041d0e9e19598e9e071e60ab0f17af3096466e2d8ab592f8ea5463dd8048f9c171e7457ef9bbe

test:
  secret_key_base: 8d09c984d4660db0d9ddb0dca065a12209d27cb84870d1547f0c9725068639db3e66a9f5c3d2548ca3c0c2e47745103a4d55b3898a8ef7687dedbb1f8cc04600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
