octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development
    - production
  development:
    master:
      adapter: mysql2
      encoding: utf8
      database: knowmad_development
      username: admin
      password: admin
      host: <%= ENV['RAILS_ENV'] == 'development' ? 'localhost' : 'mysql'  %>
      pool: 5
    slave:
      adapter: mysql2
      encoding: utf8
      reconnect: true
      database: knowmad_development
      username: admin
      password: admin
      host: <%= ENV['RAILS_ENV'] == 'development' ? 'localhost' : 'mysqlslave'  %>
      pool: 5

  production:
    master:
      adapter: mysql2
      encoding: utf8
      database: knowmad_production
      username: <%= ENV['KNOWMAD_PRODUCTION_DB_MASTER_USER'] %>
      password: <%= ENV['KNOWMAD_PRODUCTION_DB_MASTER_PASS'] %>
      host: <%= ENV['RAILS_ENV'] == 'development' ? 'localhost' : 'mysql'  %>
      pool: 5
    slave:
      adapter: mysql2
      encoding: utf8
      reconnect: true
      database: knowmad_production
      username: <%= ENV['KNOWMAD_PRODUCTION_DB_SLAVE_USER'] %>
      password: <%= ENV['KNOWMAD_PRODUCTION_DB_SLAVE_PASS'] %>
      host: <%= ENV['RAILS_ENV'] == 'development' ? 'localhost' : 'mysqlslave'  %>
      pool: 5
